version: "3.8"

services:

  # Application
  whoami:
    image: containous/whoami
    container_name: whoami
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=web,websecure" # if HTTPS (#2) add "websecure"
      - "traefik.http.routers.whoami.rule=Host(`docker.local`)"
      - "traefik.http.routers.whoami.middlewares=auth@file,secureHeaders@file" # linked to dynamic conf - Basic Auth (#1) + Security
      - "traefik.http.routers.whoami.tls.certresolver=lets-encrypt" # HTTPS (#2)
    networks:
      - traefik-net


  # Reverse proxy with SSL
  traefik:
    image: traefik:v2.5
    ports:
      - 80:80 # HTTP
      - 443:443 # HTTPS (#2)
      # - 8080:8080 # Web GUI (#3)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik_static.yml:/traefik.yml:ro # Traefik static configuration
      - ./traefik_dynamic.yml:/dynamic.yml:ro # Traefik dynamic configuration
      - ./acme.json:/acme.json # HTTPS (#2) first: touch acme.json && chmod 600 acme.json
      - ./certs:/certs:ro # HTTPS (#2) - custom SSL certificates
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
