## STATIC CONFIGURATION
log:
  level: INFO

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
